theme: "hugo-theme-novela"
baseURL: "https://farense.netlify.app/"
languageCode: "es-cl"
title: "Farense"
pygmentsstyle: 'monokai'
paginate: 6
#social:
#  twitter: "#"
#  github: "#"
#  instagram: "#"
#  linkedin: "#"
#  dribbble: "#"
#  youtube: "#"
taxonomies:
  author: authors